
redis.server: 127.0.0.1
redis.port: 6379

spring:
  jpa:
    database: MYSQL
  datasource:
    platform: mysql
    url: jdbc:mysql://192.168.0.103:3306/microservice_prescription
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver